### ISSUE TITLE
Accessing native Three.js objects from react components

### ISSUE THREAD

**Issue by PetrykowskiM** [facebook/react-360#180]
Hey there,

I would like to access the native Three.js object that is displayed when I add a `<Box>` into my render function. Is that currently possible?

#### Expected behavior
```
<Box ref={(box) => { this.box =  box }}></Box>

so that: typeof this.box.threejsObject === 'THREE.BoxGeometry'
```

I would like to get the native Object Three.js object through the above shown `this.box` handle in order to apply a custom canvas texture.

Thanks!

**Comment by andrewimm** [comment]
React VR is designed to intentionally prevent you from accessing the rendering implementation from your React code. This is because we want React VR applications to one day be able to run across a wide range of runtimes, and each of those will have a different underlying rendering implementation.

Instead I think this issue should be rephrased into how to apply a 2d canvas as the texture on any mesh. That is something we can definitely look into adding, since different runtimes can declare different texture rendering techniques. In fact, we already render offscreen canvases on demand to generate vector graphics in things like the video controls.

**Comment by PetrykowskiM** [comment]
Ok, so there is currently no possibility to render a canvas into a scene?

Can you recommend a workaround for it?

**Comment by amberroy** [comment]
Do you mean rendering a 2d canvas as the texture on any mesh?  As Andrew mentioned above this is not currently supported.  You can apply a custom texture to the [Box component](https://facebook.github.io/react-vr/docs/box.html), depending on your use case this may be a workaround.
