### ISSUE TITLE
[Question] How to rotate entire scene?

### ISSUE THREAD

**Issue by sauliusgrigaitis** [facebook/react-360#258]
Is there any way to rotate entire scene based on how user is holding the phone when opening 360? So now I see floors if I open 360 when holding the phone horizontally. I would like to see wall when I open 360 so I can keep browsing as I'm actually holding the phone in a weird vertical position.

**Comment by andrewimm** [comment]
Not entirely sure I understand. When you load the web page, it takes an initial reading of the phone's sensors and uses that as the origin, so that the camera loads at the desired starting orientation.

Can you describe the exact steps that are leading you to view the floor at initialization time instead of the wall, as expected?

**Comment by sauliusgrigaitis** [comment]
I see floors when I open WelcomeToVR demo with Chrome 59.0.3071.125 on my Nexus 5x laying on the table. I also saw same behavior on other devices at the office.

**Comment by andelar** [comment]
As sauliusgrigaitis notes, the WelcomeToVR demo indeed opens showing the floor, if the phone is laying on the table - same with iPhone.

The current behaviour has merits. I quite like it. The user has two choices at launch:
1. Pick the phone up from the table and hold it straight. As expected, the horizon is shown.
2. Leave it on the table and navigate by swiping. Now with 1.4.0 that works nicely.

If you change the current behaviour to make sensor down = world straight at launch, it's better for use case 2 but worse for use case 1. If the user picks the phone up and points it straight, phone straight will equal world up, and you can't look left because that then equals rotate Y and similar weird effects. 

(However it sounds from the above thread that the behaviour is different on different devices or different startup procedures and of course it should be consistent.)

**Comment by sauliusgrigaitis** [comment]
I think the best solution would be to pass option on initialisation should this 360 photo adjust orientation to sensors or render without adjustment. So then everyone could choose.

**Comment by Udanita** [comment]
Hi all, where is the code part i have to modify to insert a standard button that turn off the sensor? Any ideas on how to do this? A lot of smartphones have the accelerometer not working properly... it will be great to have a function to switch from case 1 to case 2. (It will be good even to know how and where to make a scroll only version). Thanks in advice.

**Comment by andrewimm** [comment]
The individual enable/disable/access of control schemes is now fully supported in React 360
