### ISSUE TITLE
Fix position of an object on a view

### ISSUE THREAD

**Issue by sepehr1313** [facebook/react-360#293]
How can I fix the position of an element on the View. for example I have three buttons in a view and I want if the camera rotates, the position of this button does not change.

**Comment by mattblackdev** [comment]
@Sepehr-Aliakbary70 Can you explain what you're trying to do a little more? Are you looking for a billboarding effect?

**Comment by Sepehr-Aliakbary70** [comment]
@mattblackdev  No I want to create a menu for a tour and I want to fix the position of this menu.
Somthing like attached photo
![untitled-1](https://user-images.githubusercontent.com/6781518/28908161-2953d862-7837-11e7-93ca-0594c2ab3bf0.jpg)

**Comment by alekszaf** [comment]
Similar problem here. What I want to achieve is to have a "Back to Menu" button visible to the user wherever they look around in the panorama. Tried to make the button follow the camera, but the effect was very laggy and it just didn't look good. The best option would be to make the button fixed within the page, just like the full-screen icon, but I am not sure if it is possible.

**Comment by amitrajput1992** [comment]
@Sepehr-Aliakbary70  If you are targeting these menu buttons to be visible only to the non-VR world, then you can add these to the index.html file of your project as standard html components on top of the canvas I say. To my understanding, if you want to fix something in the 3D world, you need to add those components to the camera object, which will make it move with the camera's rotation, but that also means that it becomes useless in VR mode, since you won't be able to perform any action on it. (Those buttons will keep on moving with the camera rotation so...). 
Recently I worked on a small project where I faced a similar problem. Decided to go with a look down menu, whenever the user sees below a certain pitch value(say -30deg), show the menu, otherwise hide it. This will work in both the non-VR and Vr world alike.

**Comment by mikearmstrong001** [comment]
I see, you are after a head locked movement.

It's probably something we should add as a property on the Panels

FYI this can look a little odd, have you thought about only resetting the location at key points? This is a technique we've used in our internal appliations

**Comment by andelar** [comment]
@Sepehr-Aliakbary70 To add another similar technique as @mikearmstrong001 mentions: 
You can position the same menu at 4 locations, at 0, 90, 180, 270 degrees and open them when the user is looking down. That has some advantages:
- There won't be menus "flying around" in the VR space 
- The user can still easily reach them whichever direction he or she is looking 
- They will be in the same spot if he/she looks back up (closing the menu) and then down again (re-opening the menu).

Good luck!

**Comment by hmontes** [comment]
Maybe an event? if a user moves the camera you can capture the movement and know how many degrees the user moved the camera.

**Comment by andrewimm** [comment]
This can now be handled by attaching your elements to a Location that is updated each frame, or by rotating a Flat Surface each frame

**Comment by mattferrin** [comment]
@andrewimm While what you're saying makes perfect sense, how to do it doesn't seem to be clearly documented. I'm currently at a loss.

**Comment by brennansaul** [comment]
@andrewimm Would you be able to show or reference existing documentation for updating location on each frame?
