### ISSUE TITLE
window event listener

### ISSUE THREAD

**Issue by fedeb95** [facebook/react-360#343]
### Description

I'm trying to use window.addEventListener("beforeunload", this.myhandler) inside componentDidMount().
The handler should send a request to a running node js server (pretty much the same request I make in componentWillMount()). I'm new to react vr so maybe I'm missing something. Even a simpler confirm() inside the handler doesn't work. Thank you in advance

#### Expected behavior
When the window is closed the handler is called
#### Actual behavior
When I close the window the handler is not called
### Reproduction
constructor(props){
        super(props);
        this.closeHandler = (ev) => { sendRequest() };
}

componentDidMount() {
        window.addEventListener('beforeunload', this.closeHandler);
}

### Additional Information

* 'react-vr' package version: react-vr@1.4.0
* 'react-vr-web' package version: react-vr-web@1.4.0 
* Operating System: Debian 8.9
* Graphics Card: Intel
* Browser: Firefox ESR 45.9.0
* VR Device: No device

**Comment by andrewimm** [comment]
React VR code runs in a web worker. Web workers do not receive unload events, since `window` is not truly a Window (https://developer.mozilla.org/en-US/docs/Web/API/Window) but a WorkerGlobalScope (https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope).
You may be able to achieve your intended behavior with a Native Module that attaches to the browser window and sends the necessary event to your React code, but without testing I'm not entirely sure what  the order of events will be there.
