### ISSUE TITLE
Are there plans to introduce native renderer?

### ISSUE THREAD

**Issue by mikkotikkanen** [facebook/react-360#428]
I'm currently doing a VR app for Gear VR and the browser version with React VR seems to cause overheating (and even force closes the Oculus Browser), whereas Unity app with similar features will run perfectly cool. I would gander this would be because of Unity running in native rendering vs browser. I saw some references that the React Native approach would enable native rendering view for React VR down the line, however what I'm not sure about is if there are any plans to move to that direction anytime soon?

**Comment by andrewimm** [comment]
You may have seen from our public talks that most of Oculus's first-party apps on Gear VR, as well as the new Rift Core 2.0 software experience, are built with our in-house version of React VR which renders directly to native.
Right now, that framework is very tightly coupled to Oculus-specific needs, and isn't something we can just drop to the public. However, we are actively exploring whether it is feasible to provide a similar framework to external developers. There's a lot of work that would need to happen to make that possible, both for building the native framework, and for updating the web one to bring APIs in line.

Right now, the biggest goal for React VR in open source is the democratization of VR content creation – both by simplifying the creation process, and by increasing distribution potential. Right now, the majority of audiences don't have VR headsets, but the web version's flexibility with 2D and mobile displays mean that you can reach them today. And, because it's on the web, distribution is as simple as sharing a link. That's our key focus today, though we acknowledge that there are plenty of things native can do that the web cannot, and we are exploring ways to bring that power to developers.
