### ISSUE TITLE
Dom Overlays are broken

### ISSUE THREAD

**Issue by moroneyk** [facebook/react-360#496]
### Code for the Dom Overlay does not work

The update to react360 seems to have broken the usual way of doing Dom Overlays. 
Previously to add a Dom Overlay we would append a child to the vr.player._wrapper object.
The react360 code structure no longer seems to support this method of doing things as there is no player object for the ReactInstance.

vr.player._wrapper.appendChild(domDashboardContainer);

Is there currently a workaround for this?

Thanks,
Kevin

*react-360@1.0.0 
*react-360-web@1.0.1 
*Mac
*Chrome/Safarw
*Cardboard

**Comment by dijana-sagit** [comment]
Hi,

I found this working for me:

`r360._parent.appendChild(domDashboardContainer);`

Regards

**Comment by moroneyk** [comment]
Thats working, thanks!

**Comment by andrewimm** [comment]
^^ this is approximately the way it should be handled now, yes. I'd personally do something like this:

```
function init(bundle, parent, options = {}) {
  const r360 = new ReactInstance(bundle, parent, {
    ...options,
  });

  parent.appendChild(domContainer);
}
```

That way, you don't need to reference any private members.

We are also working on a way to treat surfaces as DOM overlays in 2D mode, so that you don't have to duplicate your code between React 360 and HTML
