### ISSUE TITLE
VideoPlayer Volume / Loop methods not working

### ISSUE THREAD

**Issue by cjdaniel-scu** [facebook/react-360#522]
### Description
Video Player methods not working
Is this a Bug or a Feature Request?
For a Bug please explain below what you did, what you expected to happen, and what actually happens.

#### Expected behavior
Play video with audio and loop
### Reproduction

List all the steps required to encounter the issue you're reporting. These steps should be clear and concise.

An example of your code that reliably reproduces the issue is ideal.

const player = r360.compositor.createVideoPlayer('myplayer');
// Instantiate the video, but do not play it yet
player.setSource('/path/to/file.mp4','2D');
player.setVolume(volume: 1);
player.setLoop(loop: true);

// To play a video as your background, reference it by its unique id
r360.compositor.setBackgroundVideo('myplayer');
### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* 'react-360' package version: [FILL THIS OUT: get this by running `npm list react-360`]
* 'react-360-web' package version: [FILL THIS OUT: get this by running `npm list react-360-web`]
* Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?]
* Browser: [FILL THIS OUT: Oculus Browser, Chrome, Edge, Safari? Which version?]
* VR Device: [FILL THIS OUT: In or Out of VR? Headset? ]

**Comment by andrewimm** [comment]
The code you've provided isn't valid JavaScript. It should be

```js
player.setLoop(true);
```

Just checked, the above works on my sample app.

**Comment by cjdaniel-scu** [comment]
https://facebook.github.io/react-360/docs/photos-and-videos.html#displaying-panoramic-videos

Is documentation incorrect?

Ok, loop works , volume does not.
player.setVolume(1);
player.setLoop(true);

**Comment by andrewimm** [comment]
Documentation is correct. What you're seeing is a common pattern in modern JavaScript libraries to specify the types of arguments in a Typescript / Flow style. Since JS is untyped, this is the only way I can convey that loop takes a boolean, while volume takes a number.

Videos are muted by default, you will have to set Muted to false – volume already defaults to 1.0.
The reason we need to do this is because Chrome no longer allows videos to play programmatically unless they are muted. Depending on your situation, you may need to attach the setMuted(true) to a window / DOM element "click" handler. We cannot control this, it is entirely Google's doing.

**Comment by cjdaniel-scu** [comment]
Great! Got audio.
