### ISSUE TITLE
Redux with React-360

### ISSUE THREAD

**Issue by vineethariharan** [facebook/react-360#527]
Where do i place the Provider in react-360 as there is no particular root element?

**Comment by andrewimm** [comment]
React 360 is actually just an implementation of React Native, and as a result using Redux in R360 is identical to using Redux in React Native.

In both, you register certain components with the `AppRegistry`. These are your root components. You can have multiple roots as well, deriving from the same Redux store. We have an example of this in the repo, though it uses a contrived Redux-like API to avoid importing any extra libraries for the sake of the example: https://facebook.github.io/react-360/docs/example-multisurface.html

**Comment by vineethariharan** [comment]
Thanks for the quick response. I was actually trying to maintain a single store between native modules and react components. But it would create two different instances of the store. I thought it was an error with the different root components inside react, but that works fine.

**Comment by andrewimm** [comment]
I'm not sure I understand -- maintaining a store between native modules and react components? Are you trying to synchronize data between the React code and the rendering code?

They run in different execution contexts, sort of like two separate browser tabs that communicate together. However, this means they don't share any data, so you can't share a single Redux store. We do this so that even if your React code gets slow, you still maintain a high-quality 60+fps rendering experience. In this scenario, you'll need to implement event-passing in your Native Modules to send data back and forth to keep it synchronized. We've done this for a number of internal products at Oculus.

**Comment by vineethariharan** [comment]
Thanks. Exactly what I was looking for.
