### ISSUE TITLE
slerp function so that onTouch scrolls with an ease? 

### ISSUE THREAD

**Issue by Jorybraun** [facebook/react-360#625]
### Description

Feature Request, 

The onClick and onTouch is quite dramatic, 

It would be amazing to be able to ease or slerp the Quaternion like youtube 360 video. 
https://www.youtube.com/watch?v=-xNN-bJQ4vI

not sure how to do this because i slept through basic algebra.

### Solution

Add another function to the math library to ease panning.

**Comment by andrewimm** [comment]
I'm not sure I follow, events are events – can you explain how it is dramatic?

Are you implementing a hover effect using click? React 360 includes the full Animated library from React Native, which allows you to implement all sorts of interpolation between states, with delays. Learn more here: http://facebook.github.io/react-native/docs/animations

**Comment by Jorybraun** [comment]
@andrewimm , sorry andrewimm, i just realised i didnt give enough context. 

I was trying to speed up the delta, of x & y for the cameracontrollers. 

If you manipulate the X and Y values as soon as the device orientation is handled the Y axis snaps back to the original position before the touch event.

**Comment by andrewimm** [comment]
So you're specifically talking about the touch overrides available on the device orientation controller?

The device orientation controller is designed to translate device angles to camera angles. There is also functionality to introduce a touch offset, so that you don't have to move the device as far. This is implemented in a pretty lightweight manner in its current state.

I don't have the time to delve into a complete solution for you, but I can probably set you on the right track. Rather than setting the angle directly, you can set a desired destination when a touch is moved. Whenever the fill-camera method is called, you can get the current time, and compare it to the last time the method was encountered. You can either use a fixed velocity, or determine one based on the current position and the desired endpoint. Then, you can multiply the velocity by the time since the last update, and determine how far along you want to move the rotation.
You can choose to interpolate the individual euler angles, or perform a quaternion interpolation. If you went with that second choice, you'd pre-compute the destination quaternion up above, instead of the destination x/y angles, and then you can slowly update your current quaternion until it hits the desired point.

**Comment by Jorybraun** [comment]
thank you for the help thats so awesome.
