### ISSUE TITLE
I'm getting this error while trying to publish the tour sample on the web

### ISSUE THREAD

**Issue by feliIhirwe** [facebook/react-360#666]
- [ ]](#![image](https://user-images.githubusercontent.com/37334429/52735470-6c687980-2fd0-11e9-8ae3-291314cf2088.png))

Seems like it is not reading the tourOfTheChester.json file
Any help will be more appreciated! 

@andrewimm

**Comment by larrylin28** [comment]
When you want publish your app, please follow the https://facebook.github.io/react-360/docs/publish.html guidance on how to bundle your js code. It looks like your code are still trying to load from a react-native packager query(`index.vr.bundle.js?platform=vr&dev=true`) rather than a bundle file(`index.vr.bundle.js`).

**Comment by feliIhirwe** [comment]
Got it fixed.. Thanks
