### ISSUE TITLE
[Question] Performance

### ISSUE THREAD

**Issue by YasHB10** [facebook/react-360#678]
Hello, there. 

The app I made deploys a sequence of videos depending on what button the user press. I had been making some performance test on my app and I have some questions about react360 performance, I hope someone can clarify them. 

First, After several tests in the pc browser and mobile browser, I have noticed the amount of download data per video is variable even in the same device, at first I believed that  react 360 was probably making some kind of adjustment to the video to deploy it in a mobile device but after testing several times in the same device the amount of data changed from time to time. My question is:  is this because react360 sends the video in packages and some of these packages can be lost depending on the internet connection quality or is this because react360 adjusts the video depending on the device by applying some compression?

My second question: when react360 detects in which kind of device the app is running, does react360 run different processes apart of the camera adjustment? if that is the case, How does this affect the amount of downloadable data?

And last, is it possible to switch between videos from the client script?  if that is the case, How does this affect the amount of downloadable data? Which are the benefits by doing it from the react script and which by doing it from the client one?

 Thanks for your attention.

**Comment by andrewimm** [comment]
1) React 360 does not actually load the video data directly. It relies on your web browser to load the video, since it can do so much more efficiently. Any differences in byte rate are decided by the browser, then.
2) What do you mean by different processes? React 360 runs the same on each device.
3) There are no differences in loading a video from React vs client.js. In fact, when loading a video from React, it just defers to the same code used in client.js

**Comment by YasHB10** [comment]
Thank for your response
