### ISSUE TITLE
Feature Request: Possibility to adjust the IPD

### ISSUE THREAD

**Issue by Ninerian** [facebook/react-360#77]
### Description

On the Gear VR is no possibility to change the IPD, so many users are forced to squint, which raises the chance of VR sickness. An in VR menu to change it would be preferable.

### Solution

Actually you are using two Three.js cameras for left and right eye. Three.js also provides the StereoCamera Class, which has the possibility to adjust the distance. Maybe this would be more suiteable to render the VR view.

### Additional Information

* react-vr package version: 0.1.7
* react-vr-web package version: 0.1.7
* Operating System: every
* Graphics Card: every
* Browser: Carmel, Chrome on Android
* VR Device: GearVR

**Comment by andrewimm** [comment]
Under the hood, React VR gets all of its projection matrices from the WebVR API. It doesn't actually compute any IPD offsets, and this is by design: clients of the WebVR API allow the actual hardware driver to use this information when providing the transforms, projection matrices, etc. This means that a system like Rift which has both hardware and software IPD settings can properly configure the APIs in Chrome.

To adjust the IPD settings in Carmel, Chrome VR, etc, those settings would have be adjusted at a lower level that we wouldn't have control over. Otherwise, there would end up being a disconnect between a client-configured IPD setup and the precomputed view matrices arriving on the VRFrameData object.

That said, you are welcome to adjust your runtime as much as you would like to change the camera settings. If you find something that works well while still cooperating with WebVR data, I'd love to hear about it.
